# Corregir colores para que Tokyonight se vea bien
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Habilitar el mouse (útil para redimensionar paneles)
set -g mouse on

# Configurar el Prefix a Ctrl-a (es más fácil de alcanzar que Ctrl-b)
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Navegación inteligente entre paneles (Vim-Tmux-Navigator)
# Esto es lo que permite usar Ctrl + h/j/k/l
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
